import prettier from "prettier";
import { SchemaIR, TableMeta } from "../engine/types.js";
import { mapPgTypeToTs, toPascalCase } from "../engine/mapper.js";

export async function generateTypeScriptDefinitions(
  schemaIR: SchemaIR,
): Promise<string> {
  const buffer: string[] = [];

  buffer.push("/**");
  buffer.push(" * Auto-generated by pg-sync");
  buffer.push(` * Extracted at: ${schemaIR.extractedAt}`);
  buffer.push(" * Do not edit this file directly.");
  buffer.push(" */\n");

  for (const table of schemaIR.tables) {
    const interfaceName = toPascalCase(table.tableName);

    buffer.push("/**");
    buffer.push(` * Table: ${table.schema}.${table.tableName}`);
    if (table.isPartitioned) {
      buffer.push(` * Partition Strategy: ${table.partitionStrategy}`);
    }
    if (table.foreignKeys.length > 0) {
      buffer.push(" * Relations:");
      for (const fk of table.foreignKeys) {
        buffer.push(
          ` * - ${fk.columnName} -> ${fk.foreignTableName}(${fk.foreignColumnName})`,
        );
      }
    }
    buffer.push(" */");

    buffer.push(`export interface ${interfaceName} {`);

    for (const col of table.columns) {
      const tsType = mapPgTypeToTs(col.dbType, col.udtName);
      const nullableFlag = col.isNullable ? " | null" : "";
      const optionalFlag =
        col.isNullable || col.defaultValue !== null ? "?" : "";

      buffer.push(`  ${col.name}${optionalFlag}: ${tsType}${nullableFlag};`);
    }

    buffer.push("}\n");
  }

  // Generate a master schema lookup map
  buffer.push("export interface DatabaseSchema {");
  for (const table of schemaIR.tables) {
    const interfaceName = toPascalCase(table.tableName);
    buffer.push(`  ${table.tableName}: ${interfaceName};`);
  }
  buffer.push("}\n");

  const rawCode = buffer.join("\n");

  return await prettier.format(rawCode, {
    parser: "typescript",
    singleQuote: true,
    semi: true,
    tabWidth: 2,
  });
}
